### ISSUE TITLE
No timeout on awaitIdle

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#104]
https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3985/workflows/9018955f-bf7a-48ee-95f1-434763a843ec/jobs/4189 => stalled for 1 hour on `Detecting project structure` task... probably some quirk of 2021.1-BETA2. Still, it should rather crash after 10 minutes with no progress :/

**Comment by lukaszwawrzyk** [comment]
This would not happen in new probe version (not yet released as I am making sure that the design is correct by trying to use it in project with benchmarks, but I guess I will open PR now.
Something like below should be satisfying for machete use case.
`intelliJ.probe.openProject(path, WaitLogic.emptyNamedBackgroundTasks(basicCheckFrequency = 2.seconds, atMost = 10.minutes))`
And even if you don't specify anything, the default waiting logic has limit of 15 min. 
It is also possible put an arbitrary wait condition, i.e. in my benchmark code, I click to open build panel and wait for the tree in sync tab to show "failure" or "finished" and I end waiting then. Then I wait for indexing task to start, and then I measure time of indexing task.

**Comment by lukaszwawrzyk** [comment]
Fixed in 0.5.0
