### ISSUE TITLE
Migrate ide-probe artifacts away from Bintray

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#116]
:///

![image](https://user-images.githubusercontent.com/3383210/112867677-7e77da00-90bb-11eb-9819-c96b06ed4f1c.png)

**Comment by lukaszwawrzyk** [comment]
We only publish to sonatype and maven central AFAIK :D

**Comment by PawelLipski** [comment]
Hmmm but JB 3rd repo is in bintray right? 🤔 `resolvers.in(ThisBuild) += MavenRepository("jetbrains-3rd", "https://jetbrains.bintray.com/intellij-third-party-dependencies")`

**Comment by PawelLipski** [comment]
I've actually thought of that once I've seen https://github.com/JetBrains/intellij-plugin-verifier/releases/tag/v1.255 ... but maybe 3rd party deps repo hasn't been migrated out of Bintray yet (unlike intellij-plugin-verifier)

**Comment by lukaszwawrzyk** [comment]
oops :/ 
Might be good opportunity to also upgrade version of this dependency.

**Comment by lukaszwawrzyk** [comment]
Fixed in https://github.com/VirtusLab/ide-probe/pull/124
