### ISSUE TITLE
Existing IntelliJ instance provider

### ISSUE THREAD

**Issue by MichalBednarz** [VirtusLab/ide-probe#128]
Ide-probe fetches zipped IntelliJ from jetbrains artifactory, unpacks the instance, modifies config files (idea64.vmoptions, idea.properties), installs plugins. The idea is to provide a second way for the IntelliJ instance to be resolved. User should be able to specify via config file if the remote (default) instance should be fetched or if existing instance should be used. From the config perspective it will be similar to the workspace (workspace.default, workspace.existing). See `WorkspaceConfig.scala`.

Besides, `IdeProbePaths` are hardcoded. We want them to be configurable because instances can have different directory structures. Also, some instances can have their own `idea*.vmoptions` and `idea.properties`. Probe now overwrites them but they should be rather preserved and appended.

**Comment by PawelLipski** [comment]
+1, I'd especially appreciate if there was an easy setting to re-use IntelliJ instances already downloaded by Gradle

**Comment by lukaszwawrzyk** [comment]
It was already implemented. It reuses installed instance, I think, you want to reuse the zip. I created another issue https://github.com/VirtusLab/ide-probe/issues/141
