### ISSUE TITLE
`com.intellij.remoterobot:remote-fixtures:1.1.18` seems no longer available

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#162]
This is a dependency of `robot-driver_2.13:0.23.0`:

https://search.maven.org/artifact/org.virtuslab.ideprobe/robot-driver_2.13/0.23.0/jar ->

```xml
        <dependency>
            <groupId>com.intellij.remoterobot</groupId>
            <artifactId>remote-fixtures</artifactId>
            <version>1.1.18</version>
        </dependency>
```

I've got it downloaded in my Gradle cache so it must have existed:

```
$ ls ~/.gradle/caches/modules-2/files-2.1/com.intellij.remoterobot/remote-fixtures/1.1.18/
6f1e474eb54ed1cc9a33dfb7e5b23cad41dd9b7e  bbcc7b941e1fa99ec8c9448a1818f1152d502e6b
```

But now it doesn't:

https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/intellij/remoterobot/remote-fixtures/

![image](https://user-images.githubusercontent.com/3383210/163028332-42ab9046-9728-4d64-96f7-c1d068f69604.png)

Not good :// anyway, ide-probe needs to be updated

**Comment by lukaszwawrzyk** [comment]
fixed in 0.24.0
