### ISSUE TITLE
Taking screenshots and environment variables `IDEPROBE_TEST_SUITE`, `IDEPROBE_TEST_CASE` and `IDEPROBE_SCREENSHOTS_DIR`

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/ide-probe#195]
I have some problem with taking screenshots -> when I do not declare env variables `IDEPROBE_TEST_SUITE` and `IDEPROBE_TEST_CASE` (necessarily these two, declaring one variable has no effect) screenshots are not taken (I can't find them in the default location `/tmp/ide-probe/screenshots/`). 
Also when I set `IDEPROBE_SCREENSHOTS_DIR` to some value it is not consider in ide-probe - still `/tmp/ide-probe/screenshots/` is set. (It is not a big deal but it might be useful in some cases to store screenshots in specific locations not only in this default one).

**Comment by lukaszwawrzyk** [comment]
These env vars are read by IntelliJ and should be set by the driver based on config. You shouldn't need to set them. But screenshots in general might be broken, it is worth investigating.
