### ISSUE TITLE
Configurable paths for temporary files

### ISSUE THREAD

**Issue by lukaszwawrzyk** [VirtusLab/ide-probe#21]
We have some places with hardcoded `/tmp/ideprobe/" (for screenshots and cache, (actually cache is configurable)), but we use crateTmpDirectory e.g. for intellij installations and workspaces. Ideally this should be configurable, for example to persist cache when restarting PC, or to put it on faster drive/other file system etc.
I am not entirely sure if we should provide some special new file like ideprobe.global.conf located in root of resources, or just keep it scoped for all tests and users would need to include it in their base config file. But regardless, I was thinking about having something like 
```
probe.paths {
  base = "/tmp/ideprobe/"
  cache = ${HOME}"/.cache/ideprobe"
  screenshots = ${probe.paths.base}/screenshots
  reports = ${probe.paths.base}/reports
  ij-instances = ${probe.paths.base}/instances
  workspaces = ${probe.paths.base}/workspaces
}
```

And some API to access these (not sure if global or inside fixture):
```
fixture.paths.cache
fixture.paths.screenshots
val targetCloneDir = fixture.paths.base.resolve("pants-repos").create().resolve(Hash.md5("$uri-$ref"))
```

It is worth thinking how we support different OS, if someone wants a /tmp dir, it is different on mac and on windows. Perhaps with an env var `base = ${TEMP}/ideprobe`that we can make sure is set to valid temp dir or something or use a special synthetic key.

**Comment by veyga** [comment]
I'm exploring this plugin; does this still need/want to be addressed? If so, do you have preferences on a separate file versus integrating/extending the `ideprobe.conf` grammar.

**Comment by lukaszwawrzyk** [comment]
@veyga Thanks for interest in this issue :) Unfortunately it was already in progress (but not marked on github). If you would still be interested in contributing here, I think there are 2 good cases to work on:
- Windows support i.e. just making sure tests run and pass on windows
- Enabling ignored tests. Some of our tests have `@Ignore` in `ProbeDriverTest`, I think they are mostly related to building. As I remember they were failing because of a bug in scala plugin itself, perhaps it is just enough to bump to the latest nightly to make them work, or just test the same probe features on gradle project instead of sbt project that seems to be more stable.

**Comment by veyga** [comment]
Are the build tools in any way dependent on the probe, or are they simply for bootstrapping a project? It's probably best to have a suite for each tool, even if one is failing in full. Sbt is failing (as you mentioned) since it's not loading a default SDK. I tried messing around with it, but couldn't get it to load (I'm trying to find a related ticket on youTrack). I'd be happy to continue trying but am curious if Java 8 is your intended JDK for sbt builds. Loading a Scala project "tries" to load Java 8 from the relevant config. Other parts of the sources (including CI) prefer/default to 11. Also, what is the contextual difference between a BuildMessage and an IDEMessage in the context of a build? Just trying to get an overall sense of the flows of the probe/driver.

**Comment by lukaszwawrzyk** [comment]
We use build tools in these tests for sake of having a model that will be mapped to idea project (so indeed, for bootstrapping). The purpose of ProbeDriverTests is to test the probe itself, see if it calls the api in the right way and is capable of running the test. It is not that relevant which build tool it is for (we are testing the probe itself rather than intellij buildtool integration). The sdk issue should already be fixed in some recent nightly of scala plugin. If not a workaround might be to call `intelliJ.probe.preconfigureJDK()` before opening the project.
As for jdk, we use what works. Since 2020.3 it seems like intellij and scala plugin migrate to 11. Different components may use different jdk as well, it is ok.
`IdeMessage` mostly used through `probe.errors` is actually  IdeLogMessage, comming from idea.log. `BuildMessage` is message comming from build - messages reported from compiler/build tool to `Build` window, for example warnings with given file location etc.
