### ISSUE TITLE
Create `reference.conf` to keep default values for `IdeProbeConfig` (HOCON files)

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/ide-probe#217]
This issue is to avoid placing many default values directly in code and spreading them over many places. Keeping all default values for  `org.virtuslab.ideprobe.config#IdeProbeConfig` would be easier to maintain and read.

**Comment by PawelLipski** [comment]
As compared to Scala code, checking reference.conf doesn't require jumping through multiple files to figure out what keys are available

**Comment by PawelLipski** [comment]
To be confirmed with @lukaszwawrzyk whether this is desired... he's got some doubts. But I'm myself still strongly in favor
