### ISSUE TITLE
Configure display mode via HOCON configuration file instead of env variable 

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/ide-probe#218]
Now, if we want to run ide-probe with specific display-mode we need to set special env variable for it (`IDEPROBE_DISPLAY`). 
For greater consistency this configuration could be transferred into HOCON configuration file like this:
```
display {
  xvfb {
    enabled = true
   screen {
      width = 1920
      height = 1080
      depth = 24
    }
  }
}
```

**Comment by PawelLipski** [comment]
Or, to maintain compatibility:

```hocon
display {
  mode = "native"
  mode = ${?IDEPROBE_DISPLAY}   # "native" or "xvfb"

  xvfb {
    screen {
       width = 1920
       height = 1080
       depth = 24
     }
   }
}
```

**Comment by PawelLipski** [comment]
Consider updating git-machete-intellij-plugin accordingly (although might be unneeded, TBD)
