### ISSUE TITLE
Instance directory does not exist once instance is shutdown

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/ide-probe#226]
During ui tests execution within a running instance, there is a instance directory (`intellij-instance-222.3345.16-EAP-SNAPSHOT--FFkv-SzpR2mJxAtNCAHFdQ`) and a log file available (`idea.log`).
```
/root/.ideprobe-uitests/instances/intellij-instance-222.3345.16-EAP-SNAPSHOT--FFkv-SzpR2mJxAtNCAHFdQ/logs/idea.log
```
---
UI test run finishes (gradle task), instance shuts down, and as a result instance directory is empty.
```
/root/.ideprobe-uitests/instances
```

I need to access `idea.log` file. I think that the instance dir (and it's content) should be kept. 

(I found it while working on https://github.com/VirtusLab/git-machete-intellij-plugin/pull/984)

**Comment by lukaszwawrzyk** [comment]
Hm. What is your specific problem? ide-probe forwards the output from IntelliJ to stdout. This is (more or less) the same that goes to logs. Also all logs are captured and available under intelliJ.probe.messages(). Freezes and errors are automatically detected and can be shown and fail the test if they happen. 
We are removing instance as for sandboxing we create a new instance per fixture. Keeping them would quickly fill up the disk. You can also run tests with debugger, putting a breakpoint before the cleanup and then inspect intellij-instance directory.

**Comment by mkondratek** [comment]
Thanks for the reply.

1. Sadly the logger output does not go to stdout.
2. I've checked `intelliJ.probe.messages()` but only IDE messages (notifications?) are there (e.g. `IdeMessage(Info,Branch layout has been automatically discovered. Edit the layout manually if needed.,None)`) - no logs that I am interested in.
3. Breakpoint solution would not work for me. I want to access the logs (from stdout/log file) from CI run. 

Here is an example of how I use logger:
https://github.com/VirtusLab/git-machete-intellij-plugin/blob/8e57697065763501aa4095d0d86fcb5bee60fba8/frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/RediscoverSuggester.java#L46

Do you have any ideas?

**Comment by LukaszKontowski** [comment]
> There are 2 paths:
> 
> * understanding the logging and see why we don't capture these and fix it
> * add special config for ide-probe that would keep instance (or more advanced - collect diagnostics data from instance (logs, config, caches) and store it in some known location)

Second option sounds good - to copy diagnostics data into some other location before IntelliJ cleanup. I'm on it.

**Comment by mkondratek** [comment]
Cool, thanks. I ve also tried to retrieve the logs using geadle & kotlin with `doLast` task on UITests. It seemed to me that's that solution gives a random solution. Once I was able to `ls` files and see the log file, the other time the directory didn't exist. So I guess `doLast` is a dead end (at least for now).

**Comment by LukaszKontowski** [comment]
@mkondratek, @PawelLipski, @lukaszwawrzyk - maybe you have some ideas, what could be copied as the "diagnostics data" before intelliJ instance cleanup? What could be useful? Except the `./logs/` directory (which is the case for this particular issue)

**Comment by PawelLipski** [comment]
Huh I can only think of some IDE metadata, like the build number, list of installed plugins etc.

**Comment by mkondratek** [comment]
**what could be copied as the "diagnostics data" before intelliJ instance cleanup?** 
no idea
**What could be useful? Except the ./logs/ directory**
I looked into my local `~/.ideprobe-uitests/instances/` and the only interesting thing I can find there are the logs
