### ISSUE TITLE
Add `case Jar` handling in the `Resource.exsists` function

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/ide-probe#242]
The `def exists(uri: URI): Boolean` method inside https://github.com/VirtusLab/ide-probe/blob/master/core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala does not handle one possible type in pattern matching. 
`case class Jar(uri: URI) extends Resource` is not handled. The reason of this issue is to fix that - add `case` condition for the `Jar` type to handle such scenarios properly.

**Comment by LukaszKontowski** [comment]
@lukaszwawrzyk 
Do you have any knowledge, why the `case class Jar` is not handled in this pattern matching? 
https://github.com/VirtusLab/ide-probe/blob/master/core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala#L25-L33
As I would like to know, whether current logic is correct (the `from(uri)` will never be of type `Jar`) or maybe this is just an oversight that needs to be fixed?

**Comment by lukaszwawrzyk** [comment]
No code path needs this and it wasn't implemented to avoid figuring out how to do this properly AFAIR.
It is used to check if release of IntelliJ exists, but it is never located in a jar, so...
You can just match on Jar and call error("Unsupported operation (...)")
