### ISSUE TITLE
Replace default values of `IntelliJFixture` with loading from `reference.conf`

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/ide-probe#253]

**Comment by PawelLipski** [comment]
In fact, I'd do this particular thing within #252 as well... IIUC this is a subset of what #252 is about 🤔

**Comment by LukaszKontowski** [comment]
Ok, let's keep PRs small

**Comment by PawelLipski** [comment]
Esp. for `probe.resolver.intellij.{jbr,repositories}`... they shouldn't be empty lists in reference.conf
