### ISSUE TITLE
Move docs on HOCON config from docs/ to comments in reference.conf

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#254]
That's where it'd be more expected to be found, from what I've seen across the libs in Scala ecosystem

**Comment by LukaszKontowski** [comment]
+ improve existing comments inside `reference.conf` - especially for the `workspace.path.cause`

**Comment by PawelLipski** [comment]
Partly already done on #252 right? in fact, just the part about removing the docs from `docs/` can be considered (to remove duplication)

**Comment by LukaszKontowski** [comment]
Yes

**Comment by LukaszKontowski** [comment]
Note: examples from https://github.com/VirtusLab/ide-probe/blob/master/docs/custom-resolvers.md are not valid (outdated?). They contain invalid paths like `probe.resolvers.intellij.repository`

**Comment by LukaszKontowski** [comment]
could be done together with https://github.com/VirtusLab/ide-probe/issues/262 and https://github.com/VirtusLab/ide-probe/issues/265 - all three issues are for reference.conf comments
