### ISSUE TITLE
Add automated intelliJ version bump

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/ide-probe#256]
Should be done after completing https://github.com/VirtusLab/ide-probe/issues/253 - so that we will not have version hardcoded in Scala code like it is now:
```
val Latest = release("2021.2.1", "212.5080.55")
```

IntelliJ version from `reference.conf` file should be updated automatically. Could be done by using some github bot user and finding newest release from https://www.jetbrains.com/intellij-repository/releases/ - or maybe some other, smarter way.

**Comment by PawelLipski** [comment]
See https://github.com/VirtusLab/git-machete-intellij-plugin/blob/develop/buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateIntellijVersions.kt for _inspiration_ (if HTML parsing can be called this way) 😅

**Comment by LukaszKontowski** [comment]
OK, looks like this was caused by lack of version update for the `org.intellij.scala` plugin. Remember to update the `extensions/scala/tests/src/test/resources/scala.conf` file as well when bumping intellij version. Example of correct changes: https://github.com/VirtusLab/ide-probe/pull/278
