### ISSUE TITLE
Factor away duplicated reference.conf files in src/test/resources

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#259]
Follow-up to https://github.com/VirtusLab/ide-probe/pull/252/files.

Files in question:
* core/driver/tests/src/test/resources/reference.conf
* extensions/scala/tests/src/test/resources/reference.conf

Via classpath manipulation (I'd expect test classpath to already include main resources) or, if hard to achieve, then via symlinks.

**Comment by LukaszKontowski** [comment]
This is not an issue. It was just my mistake. I removed duplicates and tests are successful. Closing this issue. :)
