### ISSUE TITLE
If both `probe.intellij.version.build` and `.release` are specified, which one takes precedence?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#265]
In particular, what happens if they point to different builds?

Let's then think what can be simplified in the config... in particular, it'd be very useful it one of this keys could be explicitly used as "build or release", i.e. accept both formats. In fact, `build` can be used in this way currently (at least when `release` is NOT defined)... let's maybe make this behavior documented, if it can be relied upon

**Comment by LukaszKontowski** [comment]
`probe.intellij.version.release` takes precedence. If these two values point to two different builds - the build from `release` value will be downloaded and used. Let me add some explanation as comments in the `reference.conf` soon.

**Comment by LukaszKontowski** [comment]
could be done together with https://github.com/VirtusLab/ide-probe/issues/254 and https://github.com/VirtusLab/ide-probe/issues/262 - all three issues are for `reference.conf` comments
