### ISSUE TITLE
Change the way display mode is configured

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/ide-probe#306]
Below are three possible ways how ide-probe can be run (regarding display mode)
a) `native`
b) `xvfb`
c) `headless` mode
But, for some reason, we have two different configs for this part of logic:
`probe.driver.display` to use `native` or `xvfb`
and
`probe.driver.headless` to decide if `headless` mode should be used 
And if `probe.driver.headless == true` then values from `probe.driver.display` are in fact never used.
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/49597713/197882059-cf457b44-fc7d-46c8-8088-a47d6e94148e.png">

It is confusing for users, who want to configure ide-probe with a `.conf` file. We can change the way `ide-probe`'s display mode is configured so that it is set in **only one config** (for example - get rid of the `probe.driver.headless` config and add support for "headless" value in the `probe.driver.display` config).

**Comment by lukaszwawrzyk** [comment]
they are orthogonal in their core. You can run IJ in headless mode on machine with gui environment or on machine without it. If you really want, you could run headless IJ in xvfb, but really there is no use case for that so it was not implemented. 

It is possible to run IJ as:
ui mode with native desktop
ui mode with xvfb
headless mode with native desktop
headless mode with xvfb (not implemented and useless).

**Comment by PawelLipski** [comment]
Yeah... so how about changing the config to sth like:
* ui mode with native desktop -> `probe.driver.display = native` (as currently)
* ui mode with xvfb -> `probe.driver.display = xvfb` (as currently)
* headless mode with native desktop -> **`probe.driver.display = headless`** + deprecate `probe.driver.headless`
❓
