### ISSUE TITLE
Switching from 0.3.0 to 0.4.0 increases UI test time by 1.5x-2x

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#98]
Comparing e.g. https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3941/workflows/5d220950-c991-49c6-b9cb-27b6b5ed9517/jobs/4142, ca. 4 minutes/IDE version:

![image](https://user-images.githubusercontent.com/3383210/108915032-924b9e80-762c-11eb-9731-938dc4b06517.png)

Versus https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3940/workflows/55481c81-6d7f-4e14-b9b4-de753ef86279/jobs/4141, ca. 7 minutes/IDE version:

![image](https://user-images.githubusercontent.com/3383210/108913753-b1e1c780-762a-11eb-9c5e-fd34058b1c82.png)

I checked the diff b/w 0.3.0 and 0.4.0... `AwaitIdleParams` got new field `active` but I doubt that's cause.
`DurationAssertions` also look suspicious...

**Comment by lukaszwawrzyk** [comment]
I will need to reed through the diff, maybe I find something suspicious. Generally it is not expected. Not sure if it is possible to see what takes more time now. Is this the setup or the test itself? Only reason I can think of, is the await idle somehow waits longer, yet it shouldn't. The `active` param allows to disable waiting, so that waiting can be controlled from tests. Also soon I plan to rewrite the waiting logic, so that waiting happens in tests, rather than in intellij, and is more flexible.

**Comment by PawelLipski** [comment]
> Is this the setup or the test itself?

It's rather the test cases themselves, judging by timestamps spread across the test logs :/

**Comment by lukaszwawrzyk** [comment]
I did 0.4.0 release primarily to release the new pants and bazel extensions that were moved to this repository. I now work on running benchmarks with ide-probe, so I will spend some time on development of the core, and hopefully improve it in next version. You may want to skip this one for now. 
I forgot to reply to `DurationAssertions` concern. It should be unreated. Until you use it, it can't do anything (it is new added thing, there is no integration into existing stuff). It is a utility that allows to assert that something takes short enough, to track down if something slowed down noticably. For example: importing of project A should take no more than 5 minutes.

**Comment by PawelLipski** [comment]
> You may want to skip this one for now.

Ok, sticking to 0.3.0 then 👍🏻 

> Until you use it, it can't do anything 

Yeah, that was my impression as well

**Comment by PawelLipski** [comment]
Ok, given that v0.5.0 is released, I think we can close this one :)
